
#ifndef _DDOsnProt_H
#define _DDOsnProt_H

#define OSNPROT_DEVICE_TYPE					60003

#define IOCTL_OSN_HIDE_DISK			CTL_CODE(OSNPROT_DEVICE_TYPE, 1200, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_OSN_SHOW_DISK			CTL_CODE(OSNPROT_DEVICE_TYPE, 1201, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_OSN_DISK_READWRITE	CTL_CODE(OSNPROT_DEVICE_TYPE, 1202, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_OSN_DISK_READONLY					CTL_CODE(OSNPROT_DEVICE_TYPE, 1203, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_OSN_GET_DISK_PROTECT				CTL_CODE(OSNPROT_DEVICE_TYPE, 1204, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_OSN_CDP_PROTECT_PARTITION		CTL_CODE(OSNPROT_DEVICE_TYPE, 1205, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_OSN_CDP_UNPROTECT_PARTITION	CTL_CODE(OSNPROT_DEVICE_TYPE, 1206, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_OSN_HIDE_TRANSPARENT_DISK	    CTL_CODE(OSNPROT_DEVICE_TYPE, 1207, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_OSN_PROTECT_PM_PARTITION		CTL_CODE(OSNPROT_DEVICE_TYPE, 1208, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_OSN_UNPROTECT_PM_PARTITION	CTL_CODE(OSNPROT_DEVICE_TYPE, 1209, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_OSN_SHOW_PARTITION					CTL_CODE(OSNPROT_DEVICE_TYPE, 1210, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_OSN_HIDE_PARTITION					CTL_CODE(OSNPROT_DEVICE_TYPE, 1211, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_OSN_SHOW_TRANSPARENT_DISK	    CTL_CODE(OSNPROT_DEVICE_TYPE, 1212, METHOD_BUFFERED, FILE_ANY_ACCESS)

struct OsnCdpProtInfo
{
	LARGE_INTEGER StartingOffset;
	LARGE_INTEGER PartitionLength;
};



#endif
