#ifndef __DDOsnCache__H__H__
#define __DDOsnCache__H__H__



#define OSNCACHE_FILE_ANY_ACCESS                 0
#define OSNCACHE_METHOD_BUFFERED                 0


#define OSNCACHE_CTL_CODE( DeviceType, Function, Method, Access ) (                 \
    ((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method) \
)

#define OSN_MAKE_IOCTL(t,c)\
        (ULONG)OSNCACHE_CTL_CODE((t), 0x800+(c), OSNCACHE_METHOD_BUFFERED, OSNCACHE_FILE_ANY_ACCESS)

#define INTER_SDS                           0x0001
#define OSNCACHE_DEVICE_TYPE					60109
//IOCTL 
#define IOCTL_OSNCACHE_START_CACHE							OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,100)
#define IOCTL_OSNCACHE_STOP_INITIALIZE						OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,101)
#define IOCTL_OSNCACHE_STOP_CACHE							OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,102)


#define IOCTL_OSNCACHE_ALLOC_MEM_START						OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,202)
#define IOCTL_OSNCACHE_ALLOC_MEM_LOCK						OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,203)
#define IOCTL_OSNCACHE_ALLOC_MEM_FINISH_AND_START_CACHE		OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,204)


#define IOCTL_OSNCACHE_CLEAR_CACHE							OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,103)
#define IOCTL_OSNCACHE_RESET_READAHEADNUM					OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,104)
#define IOCTL_OSNCACHE_RESET_WRITEBEHINDNUM					OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,105)
#define IOCTL_OSNCACHE_SETDEVICE_CACHETHROUGH				OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,106)

#define IOCTL_OSNCACHE_NOTIFY_VOLUMEINFO					OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,107)

#define IOCTL_OSNCACHE_NOTIFY_CACHEVOLUME					OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,108)

#define IOCTL_OSNCACHE_RESTART_COUNTHIT						OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE, 200)
#define IOCTL_OSNCACHE_STATISTICS_HIT						OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,201)

/*
#define OSN_MAKE_IOCTL(t,c)\
        (ULONG)CTL_CODE((t), 0x800+(c), METHOD_BUFFERED, FILE_ANY_ACCESS)

#define INTER_SDS                           0x0001
#define OSNCACHE_DEVICE_TYPE					60109
//IOCTL 
#define IOCTL_OSNCACHE_START_CACHE					OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,100)
#define IOCTL_OSNCACHE_STOP_INITIALIZE				OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,101)
#define IOCTL_OSNCACHE_STOP_CACHE					OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,102)
#define IOCTL_OSNCACHE_CLEAR_CACHE					OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,103)
#define IOCTL_OSNCACHE_RESET_READAHEADNUM			OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,104)
#define IOCTL_OSNCACHE_RESET_WRITEBEHINDNUM			OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,105)
#define IOCTL_OSNCACHE_SETDEVICE_CACHETHROUGH		OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,106)


#define IOCTL_OSNCACHE_RESTART_COUNTHIT				OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE, 200)
#define IOCTL_OSNCACHE_STATISTICS_HIT				OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,201)

*/

#define lockmemory 1

struct CacheThroughInfo
{
	BOOLEAN			Flag_ThroughCache;
	ULONG			Signature;
	LARGE_INTEGER	StartingOffset;
};

struct CCacheMem
{
//	ULONG CacheSize: 31;
//	ULONG fAllocEnd: 1;


	ULONG CacheSize;
	PVOID CacheStartAddr;
};
//#define IOCTL_OSNCACHE_GET_RECOVERY_PERCENTAGE              OSN_MAKE_IOCTL(OSNCACHE_DEVICE_TYPE,103)   



#endif //ifndef __DDOsnCache__H__H__


   