#ifndef _DDOsnSp_H
#define _DDOsnSp_H

typedef struct _VOLUME_MOUNT_INFO_
{
	GUID	Guid;
	ULONG	DriveLetter;
}VOLUME_MOUNT_INFO;

#define	LOOPBACK_NAME_MAX_LEN 256//wchar 128

#define OSNSP_DEVICE_TYPE					60005

#define IOCTL_OSNSP_CREATE_LOOPBACK			CTL_CODE(OSNSP_DEVICE_TYPE, 1200, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_OSNSP_DELETE_LOOPBACK			CTL_CODE(OSNSP_DEVICE_TYPE, 1201, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_OSNSP_CHECK_LOOPBACK			CTL_CODE(OSNSP_DEVICE_TYPE, 1203, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_OSNSP_CREATE_NASDISK			CTL_CODE(OSNSP_DEVICE_TYPE, 1204, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_OSNSP_DEFINE_VOLUME_DOSNAME	CTL_CODE(OSNSP_DEVICE_TYPE, 1204, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_OSNSP_DELETE_VOLUME_DOSNAME	CTL_CODE(OSNSP_DEVICE_TYPE, 1205, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_OSNSP_CHECK_VOLUME_DOSNAME	CTL_CODE(OSNSP_DEVICE_TYPE, 1206, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif

