#ifndef OSN_CLIENT_TYPE_H_
#define OSN_CLIENT_TYPE_H_

#define OSN_CLIENT_TYPE_WINDOWS 0
#define OSN_CLIENT_TYPE_LINUX	1
#define OSN_CLIENT_TYPE_SOLARIS 2
#define OSN_CLIENT_TYPE_HP_UNIX 3
#define OSN_CLIENT_TYPE_AIX		4
#define OSN_CLIENT_TYPE_NETWARE	5

#endif
