#ifndef _OSNND_IOCTL_H_
#define _OSNND_IOCTL_H_




#define OSNND_DEVICE_TYPE					0x8000
#define OSNND_MAKE_IOCTL(t,c)\
        (ULONG)CTL_CODE((t), 0x800+(c), METHOD_BUFFERED, FILE_ANY_ACCESS)


#define OSNDF_DEVICE_TYPE					0x8400
#define OSNVF_DEVICE_TYPE					0x8800
#define OSNSS_LOOPBACK_TYPE					0x8840

typedef struct _SET_VOLUME_INFO
{
 char   TargetName[OSN_MAX_HOSTNAME];
 VOLUMEID m_VolumeId;
} SET_VOLUME_INFO,*PSET_VOLUME_INFO;

typedef enum OSNMIR_VOLUME_STATE
{
	VOLUME_STATE_DOWN,
	VOLUME_STATE_UP,
	VOLUME_STATE_FORCE_UP,
	VOLUME_STATE_SET_DISABLE
};


typedef struct _REPLICATION_INFO
{
	VOLUMEID   m_LocalVolumeID;
	VOLUMEID   m_RemoteVolumeID;
	VOLUMEID   m_BufferVolumeID;  
	BOOLEAN    m_NewAssigned;
	BOOLEAN    m_bDualPortShared;
	ULONG	   m_IncrementPercentage;
	ULONGLONG  m_LimitSize;

} REPLICATION_INFO, *PREPLICATION_INFO;

typedef struct _OSNMIR_SET_VOLUMESTATE_INFO
{
        VOLUMEID        m_VolumeID;
        OSNMIR_VOLUME_STATE         m_VolumeState;
} OSNMIR_SET_VOLUMESTATE_INFO, *POSNMIR_SET_VOLUMESTATE_INFO;

typedef struct _CFG_ARB_INFO
{
	char			TargetName[OSN_MAX_HOSTNAME];
	char			m_VolumeId[16];
	ULONG			m_Reason;
	ULONG			m_SystemIndex;
	char			m_DPStateInfo[4];
}CFG_ARB_INFO, *PCFG_ARB_INFO;

#define IOCTL_OSNND_START					OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,11)
#define IOCTL_OSNND_STOP					OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,12)
#define IOCTL_OSNND_NOTIFY_WWN				OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,13)
#define IOCTL_OSNND_NOTIFY_IPADDRESS		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,14)
#define IOCTL_OSNND_SHUTDOWN				OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,15)
#define IOCTL_OSNND_ADD_TARGETINFO			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,16)
#define IOCTL_OSNND_ADD_BACKUPINFO			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,17)
#define IOCTL_OSNND_ADD_INITIATORINFO		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,18)
#define IOCTL_OSNND_DELETE_INITIATORINFO	OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,19)
#define IOCTL_OSNND_VERIFY_INITIATOR		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,20)
#define IOCTL_OSNND_DELETE_BACKUPINFO		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,21)
#define IOCTL_OSNND_DELETE_TARGETINFO		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,22)
#define IOCTL_OSNND_GET_LINKSTATE			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,23)
#define IOCTL_OSNND_GET_TARGET_LIST			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,24)
#define IOCTL_OSNND_RESET_CLIENT			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,25)
#define IOCTL_OSNND_GET_BACKUP_STATE		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,26)
#define IOCTL_OSNND_GET_CLIENT_IPADDRESS	OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,27)
#define IOCTL_OSNND_RESET_SERVER_SESSION	OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,28)





#define IOCTL_OSNDF_TEST_SESSION_STATE		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,49)
#define IOCTL_OSNDF_GET_SIGNATURE_OFFSET	OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,50)
#define IOCTL_OSNDF_INITIALIZE				OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,51)
#define IOCTL_OSNDF_STOP_INITIALIZE			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,52)
#define IOCTL_OSNDF_CHECK_INITIALIZE		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,53)
#define IOCTL_OSNDF_GET_DEVICEINDEX			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,54)
#define IOCTL_OSNDF_SET_BACKUP				OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,55)
#define IOCTL_OSNDF_UNSET_BACKUP			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,56)
#define IOCTL_OSNDF_CLEAR_CONFIGURATION		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,57)
#define IOCTL_OSNDF_GET_DISKSIZE			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,58)
#define IOCTL_OSNDF_GET_DEVICESTATE			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,59)
#define IOCTL_OSNDF_FLUSH					OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,60)
#define IOCTL_OSNDF_SNAPSHOT				OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,61)
#define IOCTL_OSNDF_MARKER					OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,62)
#define IOCTL_OSNDF_SHUTDOWN				OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,63)
#define IOCTL_OSNDF_START					OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,64)
#define IOCTL_OSNDF_STOP					OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,65)
#define IOCTL_OSNDF_ENUM_PERF_INSTANCES		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,66)
#define IOCTL_OSNDF_GET_DEVICE_NUMBER		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,67)
#define IOCTL_OSNDF_GET_DEVICE_NAME			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,68)
#define IOCTL_OSNDF_SET_REPLICATION_MODE	OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,69)
#define IOCTL_OSNDF_SET_NOTRANSFER_PERIOD	OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,70)
#define IOCTL_OSNDF_GET_ASYNCHSTORAGE_INFO  OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,71)
#define IOCTL_OSNDF_BOOT_VOLUME				OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,72)


#define IOCTL_OSNRC_SET_TIMEMARKER			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,73)
#define IOCTL_OSNND_SET_VOLUME_READONLY		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,74)
#define	IOCTL_OSNMIR_SET_VOLUME_STATE		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,75)
#define IOCTL_OSNRC_GET_TIMEMARKER_STORAGE_INFO	OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,76)
#define IOCTL_OSNND_CFG_ARBITRATE			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,77)

//this is a internal ioctl call
#define IOCTL_OSNDF_TARGET_REPORT_LUN		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,100)
#define IOCTL_OSNDF_TARGET_GET_LUN_INFO		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,101)
#define IOCTL_OSNDF_ALL_ZERO_WRITE			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,102)




//IOCTL to SnapStreamer
#define IOCTL_OSNSS_MAKE_SNAPSHOT			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,300)
#define IOCTL_OSNSS_DELETE_SNAPSHOT			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,301)
#define IOCTL_OSNSS_CREATE_LOOPBACK			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,302)
#define IOCTL_OSNSS_DELETE_LOOPBACK			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,303)
#define IOCTL_OSNSS_SET_SNAPSHOT_VOLUME		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,304)
#define IOCTL_OSNSS_GET_SNAPSHOT_LIST		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,305)
#define IOCTL_OSNSS_GET_SNAPSHOT_INFO		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,306)
#define IOCTL_OSNSS_IS_VOLUME_LOOPBACK		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,307)
#define IOCTL_OSNSS_GET_SNAPSHOT_COUNT		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,308)
#define	IOCTL_OSNSS_GET_EXTENDEDSNAPSHOT_COUNT	OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,309)
#define IOCTL_OSNSS_GET_SNAPSHOT_UNITSIZE	OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,310)
#define	IOCTL_OSNSS_GET_VOLUMESIZE			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,311)
#define	IOCTL_OSNSS_GET_ASSOCIATED_SNAPSHOT	OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,312)

#define	IOCTL_OSNSS_RECOVER_VOLUME			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,313)
#define	IOCTL_OSNSS_RECOVER_VOLUME_DONE		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,314)
#define	IOCTL_OSNSS_RESTORE					OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,315)
#define	IOCTL_OSNSS_GET_RESTORE_PROGRESS		OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,316)
#define	IOCTL_OSNSS_GET_RESTORE_STATE			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,317)
#define	IOCTL_OSNSS_REUSE_VOLUME			OSNND_MAKE_IOCTL(OSNND_DEVICE_TYPE,318)



#endif // _OSNND_IOCTL_H_
